backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/public/images/uploads"
public_folder: "/images/uploads"
logo_url: "cms-logo.png"
collections:
  - name: "stall" # used in routes
    label: "Stalls" # used in the UI
    label_singular: "Stall" # Used in the UI, ie: "New Stall"
    identifier_field: name
    description: >
      Add a new stall by clicking the 'New Stall' button, or edit existing stalls below by selecting the stall below. NOTE changes made here will update the LIVE SITE.
    folder: "stalls"
    create: true # Allow users to create new stalls
    fields: # The fields each document in this collection have
      - { label: "Stall Name", name: "name", widget: "string", tagname: "h1" }
      - { label: "Website", name: "url", widget: "string", tagname: "h1" }
      - { label: "Facebook", name: "facebook", widget: "string", tagname: "h1" }
      - {
          label: "Instagram",
          name: "instagram",
          widget: "string",
          tagname: "h1",
        }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Stall Description", name: "description", widget: "text" }
      - {
          label: "Ethical Description",
          name: "ethicalDescription",
          widget: "text",
        }
      - label: "Stall Criteria"
        name: "criteria"
        widget: "select"
        multiple: true
        min: 1
        options:
          [
            "Fair Trade",
            "Upcycled",
            "Eco-friendly",
            "Local Produce/Local Artist",
            "Community Empowerment",
          ]
        hint: "Which ethical criteria does this stall meet? Choose at least one"
      - label: "Departments"
        label_singular: "Department"
        name: "departments"
        widget: "select"
        multiple: true
        required: true
        options:
          [
            "Health/Beauty",
            "Food/Drinks",
            "Clothing/Accessories",
            "Plants",
            "Jewellery",
            "Children/Babies",
            "Art",
            "Homewares",
            "Gifts",
            "Cleaning",
            "Pets",
          ]
        hint: "Choose one or many."
      - label: "Categories"
        label_singular: "Category"
        name: "categories"
        widget: "select"
        multiple: true
        required: false
        options:
          [
            "Vegan",
            "Plastic Free",
            "Certified Organic",
            "Handmade",
            "Waste Free",
            "Plant Based",
            "Carbon Neutral",
            "Female Empowerment",
            "First Nations",
            "Social Enterprise",
            "< 20km Tecoma Radius",
            "Refugee Advocacy",
            "Palm Oil Free",
          ]
        hint: "Choose one or many."
      - label: "Available Products"
        label_singular: "Available Product"
        name: "products"
        widget: "list"
        allow_add: true
        fields:
          - { label: "Product Name", name: "product_name", widget: "string" }
          - {
              label: "Product Description",
              name: "product_description",
              widget: "text",
            }
          - { label: "Product Image", name: "product_image", widget: "image" }
