backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "stall" # used in routes
    label: "Stall" # used in the UI
    label_singular: "Stall" # Used in the UI, ie: "New Stall"
    folder: "stalls"
    description: >
      Use this dashboard to enter new stalls or update existing stalls.

    create: true
    fields:
      - { label: "Stall", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
