backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
logo_url: "images/cms-logo.png"
collections:
  - name: "stall" # used in routes
    label: "Stalls" # used in the UI
    label_singular: "Stall" # Used in the UI, ie: "New Stall"
    identifier_field: name
    description: >
      Add a new stall by clicking the 'New Stall' button, or edit existing stalls below.
    folder: "stalls"
    create: true # Allow users to create new stalls
    fields: # The fields each document in this collection have
      - { label: "Stall Name", name: "name", widget: "string", tagname: "h1" }
      - { label: "Website", name: "url", widget: "string", tagname: "h1" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          [
            "Fair Trade",
            "Upcycled",
            "Eco Friendly",
            "Locally Made",
            "Community Empowerment",
          ]
          hint: "Choose one or many"
      - label: "Keywords"
        name: "keywords"
        widget: "select"
        multiple: true
        options: ["Vegan", "Plastic-free", "Clothing", "Jewellery", "Women-run"]
        hint: "Choose one or many"
      - label: "Available Products"
        label_singular: "Available Product"
        name: "products"
        widget: "list"
        allow_add: true
        fields: # the stall's featured items
          - label: "Product"
            name: "product"
            widget: "object"
            fields:
              - { label: 'Product Name', name: 'product-name', widget: 'string' }
              - { label: 'Product Description', name: 'product-description', widget: 'string' }
              - { label: 'Product Image', name: 'product-image', widget: 'image' }


